/* Generated by spangap-core/scripts/ota-keygen.py - do not edit. */
#ifndef SPANGAP_OTA_PUBKEY_H
#define SPANGAP_OTA_PUBKEY_H

static const char OTA_PUBKEY_PEM[] =
    "-----BEGIN PUBLIC KEY-----\n"
    "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEk/2rpvKOj8OxZARBQ600EeWrvJey\n"
    "jUB+ATGGq3GAu1i2XSDx39ayTExpJHivZSCg8OHUJ+qIdM85tMScdVaKDw==\n"
    "-----END PUBLIC KEY-----\n";

static const unsigned OTA_PUBKEY_PEM_LEN = sizeof(OTA_PUBKEY_PEM);

#endif
