"""One-shot helper to mint pinned test identities.

Usage:
    .venv/bin/python tests/mint_fixed_keys.py 8 > tests/fixed_keys.py

Generates N (priv_hex, identity_hash_hex) tuples and emits a Python module
of the same shape as upstream Reticulum's `fixed_keys` list in tests/link.py.
The pinned keys make destination hashes stable across runs, which keeps
test logs and rnsd.log grep-able. Re-run only when we genuinely need more
keys; existing assertions hard-code hashes from the committed file.
"""

import sys

import RNS


def main(n: int) -> int:
    print('"""Pinned test identities — regenerated by mint_fixed_keys.py."""')
    print()
    print("# (private_hex, identity_hash_hex) tuples.")
    print("# Identity hash is the truncated-SHA256 of the public key bundle;")
    print("# destinations derive their own hash from (identity_hash, app, aspects).")
    print("FIXED_KEYS = [")
    for _ in range(n):
        identity = RNS.Identity()
        priv = identity.get_private_key().hex()
        ihash = identity.hash.hex()
        print(f'    ("{priv}", "{ihash}"),')
    print("]")
    return 0


if __name__ == "__main__":
    sys.exit(main(int(sys.argv[1]) if len(sys.argv) > 1 else 8))
